name: aws-cli
description: aws cli 
author: Comori

# Define your inputs here.
inputs:
  aws-access-key-id:
    description: "AWS access key id to access your bucket"
    required: true
  aws-secret-access-key:
    description: "AWS secret access key to access your bucket"
    required: true
  aws-region:
    description: "AWS region where your bucket is located"
    required: true
    default: us-east-1
  module:
    required: true
    default: s3
  bucket:
    description: "AWS s3 bucket to store the artifacts"
  files:
    description: Who to greet
    required: true

# Define your outputs here.
outputs:
  time:
    description: The time we greeted you

runs:
  using: node20
  main: dist/index.js
